/*
 * Sample
 * Join event streams in real-time to setup complex alerts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package io.drdroid.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.drdroid.client.model.EventIngestRequestDataEventsInnerKvsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.drdroid.client.JSON;

/**
 * EventIngestRequestDataEventsInner
 */
@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class EventIngestRequestDataEventsInner {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private Double timestamp;

  public static final String SERIALIZED_NAME_KVS = "kvs";
  @SerializedName(SERIALIZED_NAME_KVS)
  private List<EventIngestRequestDataEventsInnerKvsInner> kvs = null;

  public EventIngestRequestDataEventsInner() {
  }

  public EventIngestRequestDataEventsInner name(String name) {

    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Schedule Delivery", value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {

    
    
    
    this.name = name;
  }


  public EventIngestRequestDataEventsInner timestamp(Double timestamp) {

    
    
    
    
    this.timestamp = timestamp;
    return this;
  }

  public EventIngestRequestDataEventsInner timestamp(Integer timestamp) {

    
    
    
    
    this.timestamp = timestamp.doubleValue();
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1683009771000", value = "")

  public Double getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(Double timestamp) {

    
    
    
    this.timestamp = timestamp;
  }


  public EventIngestRequestDataEventsInner kvs(List<EventIngestRequestDataEventsInnerKvsInner> kvs) {

    
    
    
    
    this.kvs = kvs;
    return this;
  }

  public EventIngestRequestDataEventsInner addKvsItem(EventIngestRequestDataEventsInnerKvsInner kvsItem) {
    if (this.kvs == null) {
      this.kvs = new ArrayList<>();
    }
    this.kvs.add(kvsItem);
    return this;
  }

   /**
   * Get kvs
   * @return kvs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<EventIngestRequestDataEventsInnerKvsInner> getKvs() {
    return kvs;
  }


  public void setKvs(List<EventIngestRequestDataEventsInnerKvsInner> kvs) {

    
    
    
    this.kvs = kvs;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the EventIngestRequestDataEventsInner instance itself
   */
  public EventIngestRequestDataEventsInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventIngestRequestDataEventsInner eventIngestRequestDataEventsInner = (EventIngestRequestDataEventsInner) o;
    return Objects.equals(this.name, eventIngestRequestDataEventsInner.name) &&
        Objects.equals(this.timestamp, eventIngestRequestDataEventsInner.timestamp) &&
        Objects.equals(this.kvs, eventIngestRequestDataEventsInner.kvs)&&
        Objects.equals(this.additionalProperties, eventIngestRequestDataEventsInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, timestamp, kvs, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventIngestRequestDataEventsInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    kvs: ").append(toIndentedString(kvs)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("timestamp");
    openapiFields.add("kvs");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EventIngestRequestDataEventsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!EventIngestRequestDataEventsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EventIngestRequestDataEventsInner is not found in the empty JSON string", EventIngestRequestDataEventsInner.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("kvs") != null && !jsonObj.get("kvs").isJsonNull()) {
        JsonArray jsonArraykvs = jsonObj.getAsJsonArray("kvs");
        if (jsonArraykvs != null) {
          // ensure the json data is an array
          if (!jsonObj.get("kvs").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `kvs` to be an array in the JSON string but got `%s`", jsonObj.get("kvs").toString()));
          }

          // validate the optional field `kvs` (array)
          for (int i = 0; i < jsonArraykvs.size(); i++) {
            EventIngestRequestDataEventsInnerKvsInner.validateJsonObject(jsonArraykvs.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EventIngestRequestDataEventsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EventIngestRequestDataEventsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EventIngestRequestDataEventsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EventIngestRequestDataEventsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<EventIngestRequestDataEventsInner>() {
           @Override
           public void write(JsonWriter out, EventIngestRequestDataEventsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public EventIngestRequestDataEventsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             EventIngestRequestDataEventsInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EventIngestRequestDataEventsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EventIngestRequestDataEventsInner
  * @throws IOException if the JSON string is invalid with respect to EventIngestRequestDataEventsInner
  */
  public static EventIngestRequestDataEventsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EventIngestRequestDataEventsInner.class);
  }

 /**
  * Convert an instance of EventIngestRequestDataEventsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

