/**
 * Sample
 * Join event streams in real-time to setup complex alerts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

import { AxiosRequestConfig } from "axios";
import {
  EventApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { DrdroidCustom } from "./client-custom";

export class Drdroid extends DrdroidCustom {
  readonly event: EventApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.event = new EventApi(configuration);
  }

}
