/*
 * Sample
 * Join event streams in real-time to setup complex alerts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.EventIngestRequest;
import com.konfigthis.client.model.EventIngestRequestData;
import com.konfigthis.client.model.EventIngestResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EventApi
 */
@Disabled
public class EventApiTest {

    private static EventApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new EventApi(apiClient);
    }

    /**
     * Ingestion V2
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ingestTest() throws ApiException {
        EventIngestRequestData data = null;
        String X_REQUEST_ORG = null;
        EventIngestResponse response = api.ingest(data, X_REQUEST_ORG)
                .execute();
        // TODO: test validations
    }

}
