/* tslint:disable */
/* eslint-disable */
/**
 * Sample
 * Join event streams in real-time to setup complex alerts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface EventIngestRequestDataEventsInnerKvsInnerValue
 */
export interface EventIngestRequestDataEventsInnerKvsInnerValue {
    /**
     * 
     * @type {string}
     * @memberof EventIngestRequestDataEventsInnerKvsInnerValue
     */
    'string_value'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EventIngestRequestDataEventsInnerKvsInnerValue
     */
    'bool_value'?: boolean;
}

