/* tslint:disable */
/* eslint-disable */
/**
 * Sample
 * Join event streams in real-time to setup complex alerts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { EventIngestRequestData } from './event-ingest-request-data';

/**
 * 
 * @export
 * @interface EventIngestRequest
 */
export interface EventIngestRequest {
    /**
     * 
     * @type {EventIngestRequestData}
     * @memberof EventIngestRequest
     */
    'data': EventIngestRequestData;
}

