/* tslint:disable */
/* eslint-disable */
/**
 * Sample
 * Join event streams in real-time to setup complex alerts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { EventIngestRequestDataEventsInnerKvsInner } from './event-ingest-request-data-events-inner-kvs-inner';

/**
 * 
 * @export
 * @interface EventIngestRequestDataEventsInner
 */
export interface EventIngestRequestDataEventsInner {
    /**
     * 
     * @type {string}
     * @memberof EventIngestRequestDataEventsInner
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof EventIngestRequestDataEventsInner
     */
    'timestamp'?: number;
    /**
     * 
     * @type {Array<EventIngestRequestDataEventsInnerKvsInner>}
     * @memberof EventIngestRequestDataEventsInner
     */
    'kvs'?: Array<EventIngestRequestDataEventsInnerKvsInner>;
}

