/*
 * Sample
 * Join event streams in real-time to setup complex alerts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EventIngestRequestDataEventsInnerKvsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EventIngestRequestDataEventsInner
 */
public class EventIngestRequestDataEventsInnerTest {
    private final EventIngestRequestDataEventsInner model = new EventIngestRequestDataEventsInner();

    /**
     * Model tests for EventIngestRequestDataEventsInner
     */
    @Test
    public void testEventIngestRequestDataEventsInner() {
        // TODO: test EventIngestRequestDataEventsInner
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'kvs'
     */
    @Test
    public void kvsTest() {
        // TODO: test kvs
    }

}
