/*
 * Sample
 * Join event streams in real-time to setup complex alerts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EventIngestRequestDataEventsInnerKvsInnerValue
 */
public class EventIngestRequestDataEventsInnerKvsInnerValueTest {
    private final EventIngestRequestDataEventsInnerKvsInnerValue model = new EventIngestRequestDataEventsInnerKvsInnerValue();

    /**
     * Model tests for EventIngestRequestDataEventsInnerKvsInnerValue
     */
    @Test
    public void testEventIngestRequestDataEventsInnerKvsInnerValue() {
        // TODO: test EventIngestRequestDataEventsInnerKvsInnerValue
    }

    /**
     * Test the property 'stringValue'
     */
    @Test
    public void stringValueTest() {
        // TODO: test stringValue
    }

    /**
     * Test the property 'boolValue'
     */
    @Test
    public void boolValueTest() {
        // TODO: test boolValue
    }

}
