/*
 * Sample
 * Join event streams in real-time to setup complex alerts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EventIngestRequestDataEventsInnerKvsInnerValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EventIngestRequestDataEventsInnerKvsInner
 */
public class EventIngestRequestDataEventsInnerKvsInnerTest {
    private final EventIngestRequestDataEventsInnerKvsInner model = new EventIngestRequestDataEventsInnerKvsInner();

    /**
     * Model tests for EventIngestRequestDataEventsInnerKvsInner
     */
    @Test
    public void testEventIngestRequestDataEventsInnerKvsInner() {
        // TODO: test EventIngestRequestDataEventsInnerKvsInner
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
